/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TfmRouteImport } from './routes/tfm'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as AcercaRouteImport } from './routes/acerca'
import { Route as IndexRouteImport } from './routes/index'

const TfmRoute = TfmRouteImport.update({
  id: '/tfm',
  path: '/tfm',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const AcercaRoute = AcercaRouteImport.update({
  id: '/acerca',
  path: '/acerca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acerca': typeof AcercaRoute
  '/checklist': typeof ChecklistRoute
  '/recursos': typeof RecursosRoute
  '/resultados': typeof ResultadosRoute
  '/tfm': typeof TfmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acerca': typeof AcercaRoute
  '/checklist': typeof ChecklistRoute
  '/recursos': typeof RecursosRoute
  '/resultados': typeof ResultadosRoute
  '/tfm': typeof TfmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acerca': typeof AcercaRoute
  '/checklist': typeof ChecklistRoute
  '/recursos': typeof RecursosRoute
  '/resultados': typeof ResultadosRoute
  '/tfm': typeof TfmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acerca'
    | '/checklist'
    | '/recursos'
    | '/resultados'
    | '/tfm'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/acerca' | '/checklist' | '/recursos' | '/resultados' | '/tfm'
  id:
    | '__root__'
    | '/'
    | '/acerca'
    | '/checklist'
    | '/recursos'
    | '/resultados'
    | '/tfm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcercaRoute: typeof AcercaRoute
  ChecklistRoute: typeof ChecklistRoute
  RecursosRoute: typeof RecursosRoute
  ResultadosRoute: typeof ResultadosRoute
  TfmRoute: typeof TfmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tfm': {
      id: '/tfm'
      path: '/tfm'
      fullPath: '/tfm'
      preLoaderRoute: typeof TfmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acerca': {
      id: '/acerca'
      path: '/acerca'
      fullPath: '/acerca'
      preLoaderRoute: typeof AcercaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcercaRoute: AcercaRoute,
  ChecklistRoute: ChecklistRoute,
  RecursosRoute: RecursosRoute,
  ResultadosRoute: ResultadosRoute,
  TfmRoute: TfmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
